ingress:
  hostname: www.pling.org.uk
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: "kube-system-redirect-https@kubernetescrd"
  tls:
    - hosts:
        - www.pling.org.uk
        - pling.org.uk
      secretName: www-pling-org-uk-tls
  probe:
    enabled: true

mariadb-cluster:
  physicalBackups:
    - name: nightly
      schedule:
        cron: "45 3 * * *"
      storage:
        s3:
          bucket: coven-backups
          prefix: mariadb/whereisthenorthreally
          region: europe-west2
          endpoint: https://storage.googleapis.com
          accessKeyIdSecretKeyRef:
            name: whereisthenorthreally-gcp-backups
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretKeyRef:
            name: whereisthenorthreally-gcp-backups
            key: AWS_SECRET_ACCESS_KEY
      compression: gzip
